# Nightlight — display colour-temperature management (see ./README.md).
#
# This module owns the Nix-side glue for the nightlight subsystem:
#   * the wl-gammarelay-rs relay (the single writer of display gamma),
#   * the baseline dawn/dusk curve timer,
#   * the bedtime on/off schedule timers,
#   * the generated schedule config (single source of truth), and
#   * the symlinks for the engine + menu scripts.
#
# The behaviour lives in the Stow-managed scripts under
# base/desktop/.local/bin/ (nightlight.sh, nightlight-menu.sh) so the exact
# same logic runs on non-NixOS installs; this file only wires them into
# systemd and keeps the schedule in lockstep with the timer OnCalendar values.
{ config, pkgs, dotfilesPath, ... }:

let
  basePath = "${dotfilesPath}/base/desktop";
  link = file: config.lib.file.mkOutOfStoreSymlink "${basePath}/${file}";

  # Single source of truth for the bedtime schedule. These values generate both
  # the systemd timer OnCalendar entries AND the ~/.config/nightlight/config
  # file the scripts read, so the timer fire time and the script's schedule
  # math can never drift apart. Change the schedule here, then run nh os switch.
  bedtimeHour = 21; # 0-23, when the bedtime profile activates (9pm)
  wakeHour = 7; # 0-23, when the bedtime profile deactivates (7am)
  pauseMinutes = 30; # default pause length
  fadeSeconds = 5; # gamma fade for manual toggles
  windDownSeconds = 60; # gentle gamma fade for the scheduled 9pm activation
  pad2 = n: if n < 10 then "0${toString n}" else toString n;

  # Shared environment for the scheduled/oneshot services: they run outside the
  # interactive shell, so they need PATH to find busctl/gammastep/notify-send
  # and the nightlight script. WAYLAND_DISPLAY is imported into the user manager
  # at session start (see sway/config); the D-Bus calls reach the session bus
  # via the default $XDG_RUNTIME_DIR/bus socket, so no DBUS_SESSION_BUS_ADDRESS
  # is needed.
  serviceEnv = [ "PATH=/run/current-system/sw/bin:%h/.local/bin" ];
in
{
  home.file = {
    ".local/bin/nightlight.sh".source = link ".local/bin/nightlight.sh";
    ".local/bin/nightlight-menu.sh".source = link ".local/bin/nightlight-menu.sh";
  };

  # Generated bedtime schedule — single source of truth (see let-bindings).
  xdg.configFile."nightlight/config".text = ''
    # Generated by nix/modules/home/services/nightlight/default.nix — do not edit by hand.
    BEDTIME_HOUR=${toString bedtimeHour}
    WAKETIME_HOUR=${toString wakeHour}
    PAUSE_MINUTES=${toString pauseMinutes}
    FADE_SECONDS=${toString fadeSeconds}
    WINDDOWN_SECONDS=${toString windDownSeconds}
  '';

  # ---------------------------------------------------------------------------
  # wl-gammarelay-rs — persistent D-Bus gamma relay (the single writer)
  # ---------------------------------------------------------------------------
  #
  # Holds the wlr-gamma-control Wayland lease for the entire session so that
  # both the baseline curve and the bedtime profile can update
  # temperature/brightness via a simple busctl call rather than killing and
  # restarting a daemon (which races on the exclusive lease and fails silently
  # on NixOS where the binary is wrapped).

  # NOTE: graphical-session.target is never activated in this setup — sway is
  # launched bare (greetd), not via systemd session integration — so the
  # After/PartOf/WantedBy=graphical-session.target lines below are INERT. These
  # units actually start from sway's `exec` (base/desktop/.config/sway/config)
  # and the bedtime units run via timers.target. The target wiring is kept for
  # consistency with the rest of desktop.nix (kanshi etc.) and in case sway
  # gains systemd session binding later.
  systemd.user.services.wl-gammarelay-rs = {
    Unit = {
      Description = "wl-gammarelay-rs D-Bus gamma relay";
      After = [ "graphical-session.target" ];
      PartOf = [ "graphical-session.target" ];
    };
    Service = {
      # Type=dbus + BusName means systemd marks the unit "started" only once the
      # relay owns its bus name. (The relay claims the name early, just before it
      # binds the Wayland gamma-control; a set-property landing in that sub-ms gap
      # isn't lost — the relay replays its current state onto outputs as they
      # bind.) This makes `After=` on the consumers below meaningful: a curve or
      # bedtime tick can't fire before the relay exists and have its write dropped.
      Type = "dbus";
      BusName = "rs.wl-gammarelay";
      ExecStart = "${pkgs.wl-gammarelay-rs}/bin/wl-gammarelay-rs";
      Restart = "on-failure";
      RestartSec = "1s";
    };
    Install = {
      WantedBy = [ "graphical-session.target" ];
    };
  };

  # ---------------------------------------------------------------------------
  # Baseline dawn/dusk curve
  # ---------------------------------------------------------------------------
  #
  # Periodically calculates the current dawn/dusk colour temperature using
  # gammastep in dummy mode (no Wayland connection needed) and pushes it to
  # wl-gammarelay-rs via D-Bus. This is the "always on" night light. The
  # bedtime profile stops this timer and sets the bedtime temp directly; pausing or
  # turning bedtime off restarts it (OnActiveSec=0s fires immediately on
  # restart, so the curve value is re-applied at once).

  systemd.user.services.nightlight-curve = {
    Unit = {
      Description = "Push dawn/dusk curve temperature to wl-gammarelay-rs";
      # Wants (not Requires): we want the ordering of `After` so a tick can't run
      # before the relay owns the name, but the script tolerates an absent relay
      # (every busctl call is `|| true`), so a relay failure must not fail this
      # unit or couple it to relay restarts.
      Wants = [ "wl-gammarelay-rs.service" ];
      After = [ "wl-gammarelay-rs.service" ];
      # The script stops/restarts this oneshot on every bedtime on/off; disable
      # the start-rate limiter so that churn can never wedge the curve as failed.
      StartLimitIntervalSec = 0;
    };
    Service = {
      Type = "oneshot";
      ExecStart = "%h/.local/bin/nightlight.sh --gamma-update";
      Environment = serviceEnv;
    };
  };

  systemd.user.timers.nightlight-curve = {
    Unit = {
      Description = "Periodic dawn/dusk curve updates for wl-gammarelay-rs";
    };
    Timer = {
      OnActiveSec = "0s";
      OnUnitActiveSec = "3min";
      AccuracySec = "30s";
    };
    Install = {
      WantedBy = [ "timers.target" ];
    };
  };

  # ---------------------------------------------------------------------------
  # Bedtime profile scheduling
  # ---------------------------------------------------------------------------
  #
  # Two calendar timers fire the on (9pm) and off (7am) services.
  # Persistent=true means: if the timer fires while the session is inactive
  # (laptop suspended, user not yet logged in), it will fire immediately the
  # next time the session comes up. This covers the "logged in at 10pm" case
  # and the "woke from suspend after 7am" case without any polling daemon.
  #
  # The on service calls --schedule-activate, which respects a DISABLED state
  # written by the user choosing "Skip Tonight". The off service calls
  # --schedule-deactivate, which clears NIGHT states and resets any lingering
  # DISABLED state from the previous night.

  systemd.user.services.nightlight-bedtime-on = {
    Unit = {
      Description = "Nightlight bedtime profile — scheduled activation";
      # Wants (not Requires): order after the relay, but a missed Persistent
      # catch-up must not be lost if the relay can't start (Requires would fail
      # the activation as a dependency failure); the script no-ops without it.
      Wants = [ "wl-gammarelay-rs.service" ];
      After = [ "graphical-session.target" "wl-gammarelay-rs.service" ];
      PartOf = [ "graphical-session.target" ];
    };
    Service = {
      Type = "oneshot";
      ExecStart = "%h/.local/bin/nightlight.sh --schedule-activate";
      # The wind-down fade blocks for windDownSeconds; keep the start timeout
      # comfortably above it so a longer wind-down can't be killed mid-fade.
      TimeoutStartSec = "5min";
      Environment = serviceEnv;
    };
  };

  systemd.user.timers.nightlight-bedtime-on = {
    Unit = {
      Description = "Nightlight bedtime profile — activate at scheduled bedtime";
    };
    Timer = {
      # Derived from bedtimeHour (single source of truth, top of this file).
      OnCalendar = "*-*-* ${pad2 bedtimeHour}:00:00";
      AccuracySec = "30s";
      # Fire immediately on next session start if the scheduled time was missed
      Persistent = true;
    };
    Install = {
      WantedBy = [ "timers.target" ];
    };
  };

  systemd.user.services.nightlight-bedtime-off = {
    Unit = {
      Description = "Nightlight bedtime profile — scheduled deactivation";
      Wants = [ "wl-gammarelay-rs.service" ];
      After = [ "graphical-session.target" "wl-gammarelay-rs.service" ];
      PartOf = [ "graphical-session.target" ];
    };
    Service = {
      Type = "oneshot";
      ExecStart = "%h/.local/bin/nightlight.sh --schedule-deactivate";
      Environment = serviceEnv;
    };
  };

  systemd.user.timers.nightlight-bedtime-off = {
    Unit = {
      Description = "Nightlight bedtime profile — deactivate at scheduled wake time";
    };
    Timer = {
      # Derived from wakeHour (single source of truth, top of this file).
      OnCalendar = "*-*-* ${pad2 wakeHour}:00:00";
      AccuracySec = "30s";
      Persistent = true;
    };
    Install = {
      WantedBy = [ "timers.target" ];
    };
  };
}
